# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Warema Bridge
version: "0.1.1-alpha.4"
slug: "warema-bridge"
description: "Control your Warema WMS system"
url: "https://github.com/koanbock/addon-warema-bridge"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
boot: auto
startup: services
hassio_api: true
map:
  - share:rw
options:
  wms_serial_port: null
schema:
  wms_key: "str?"
  wms_pan_id: "str?"
  wms_channel: "int?"
  wms_serial_port: "device(subsystem=tty)"
  ignored_devices: "str?"
  force_devices: "str?"
image: "koanbock/addon-warema-bridge"
services: [
    "mqtt:need"
  ]